# Generated by Django 5.0.6 on 2024-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='id_grupo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='id_reseña',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID: '),
        ),
    ]
