# Generated by Django 5.0.6 on 2024-12-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros_categorias',
            name='id_libro_categoria',
        ),
        migrations.AddField(
            model_name='libros',
            name='categorias',
            field=models.ManyToManyField(through='inicio.Libros_Categorias', to='inicio.categorias'),
        ),
        migrations.AddField(
            model_name='libros_categorias',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libros_categorias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.categorias'),
        ),
        migrations.AlterField(
            model_name='libros_categorias',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.libros'),
        ),
    ]
