# Generated by Django 5.0.6 on 2024-11-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_grupos_id_grupo_alter_reseñas_id_reseña'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libros_categorias',
            options={},
        ),
        migrations.AlterField(
            model_name='libros_categorias',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.categorias', verbose_name='ID:'),
        ),
        migrations.AlterField(
            model_name='libros_categorias',
            name='id_libro_categoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID: '),
        ),
    ]
