# Generated by Django 5.0.6 on 2024-11-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_libros_categorias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/', verbose_name='Imagen del Libro'),
        ),
        migrations.AddField(
            model_name='reseñas',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='inicio.libros', verbose_name='Libro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libros',
            name='ISBN',
            field=models.CharField(max_length=100, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='año',
            field=models.DateField(verbose_name='Año de Publicación'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='id_libro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='calificacion',
            field=models.IntegerField(verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='id_reseña',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
