# Generated by Django 5.0.6 on 2024-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_libros_imagen_reseñas_libro_alter_libros_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='año',
            field=models.IntegerField(verbose_name='Año de Publicación'),
        ),
        migrations.AddIndex(
            model_name='libros',
            index=models.Index(fields=['ISBN'], name='inicio_libr_ISBN_810b74_idx'),
        ),
        migrations.AddIndex(
            model_name='libros',
            index=models.Index(fields=['año'], name='inicio_libr_año_c7e410_idx'),
        ),
        migrations.AddIndex(
            model_name='libros',
            index=models.Index(fields=['autor'], name='inicio_libr_autor_1af898_idx'),
        ),
    ]
