# Generated by Django 5.0.6 on 2024-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_libros_descripción'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='libros',
            name='año',
            field=models.DateField(verbose_name='Año de Publicación'),
        ),
    ]
