# Generated by Django 3.2.4 on 2024-11-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20241126_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_grupo',
        ),
    ]
