# Generated by Django 5.0.6 on 2024-12-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_comentariocontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros/archivos/', verbose_name='Archivo'),
        ),
    ]
