# Generated by Django 5.0.6 on 2024-12-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_libros_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='archivo',
        ),
    ]
