# Generated by Django 5.0.6 on 2024-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_remove_libros_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros/archivos/', verbose_name='Archivo'),
        ),
    ]
