# Generated by Django 5.0.6 on 2024-12-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_libros_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descargas',
            old_name='id_libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='descargas',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='libros_categorias',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='libros_categorias',
            old_name='id_libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='ver_libros',
            old_name='id_libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='ver_libros',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
