# Generated by Django 5.0.6 on 2024-12-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_rename_id_libro_descargas_libro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros_categorias',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='libros_categorias',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='ver_libros',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='ver_libros',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Descargas',
        ),
        migrations.DeleteModel(
            name='Libros_Categorias',
        ),
        migrations.DeleteModel(
            name='Ver_Libros',
        ),
    ]
