# Generated by Django 5.0.6 on 2024-12-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_remove_libros_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descargas',
            fields=[
                ('id_descarga', models.AutoField(primary_key=True, serialize=False, verbose_name='ID: ')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de descarga: ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.libros', verbose_name='ID_Libro: ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario')),
            ],
            options={
                'verbose_name': 'Descarga',
                'verbose_name_plural': 'Descargas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Libros_Categorias',
            fields=[
                ('id_libro_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID: ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.categorias', verbose_name='ID:')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.libros', verbose_name='Libros: ')),
            ],
        ),
        migrations.CreateModel(
            name='Ver_Libros',
            fields=[
                ('id_ver_libro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID: ')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.libros', verbose_name='ID_Libro: ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID_Usuario')),
            ],
            options={
                'verbose_name': 'Ver Libro',
                'verbose_name_plural': 'Ver Libros',
                'ordering': ['-created'],
            },
        ),
    ]
